### ISSUE TITLE
Prevents open-last-project from working properly

### ISSUE THREAD

**Issue by ricardograca** [ahuth/preview-tabs#15]
When preview-tabs is installed [atom-open-last-project](https://github.com/danielmahon/atom-open-last-project) can't open the last session's files. Apparently it tries to open all of them, but they are opened as previews, so only the very last file is opened (as a preview) after starting Atom.

Not sure if this is related to #13, or if it's even possible to fix. Maybe only open files as previews if a file is opened by a user, if it is possible to detect that it was opened by a user, not by another package.

**Comment by ricardograca** [comment]
Closing this because the `preview-tabs` package is no longer necessary since Atom 1.6.0 which has the same functionality built-in and the reported issue doesn't occur anymore with this built-in functionality.

**Comment by ahuth** [comment]
Thanks!
