### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by MateuszG** [ahuth/preview-tabs#21]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
new PreviewTabsPaneController (atom/packages/preview-tabs/lib/preview-tabs-pane-controller.coffee:12:63)
```

**Comment by ahuth** [comment]
Thanks for bringing this up. For now, though, this atom package is deprecated.

**Comment by krainboltgreene** [comment]
Wait, why is it deprecated?

**Comment by ahuth** [comment]
By deprecated, I mean that I'm no longer working on it. I just don't have motivation or the need for it right now.
